# Generated by Django 5.0.6 on 2024-06-20 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alldatatypesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_field',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/images/'),
            preserve_default=False,
        ),
    ]
